repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1024"] # Увеличить до 1 МБ
        exclude: |
          (?x)^(
            uv\.lock|
            .*\.lock|
            \.dvc/.*
          )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length=90"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile=black", "--line-length=90"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-simplify
        args:
          - "--max-line-length=90"
          - "--extend-ignore=E203,W503,D100"
          - "--max-complexity=10"

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json, dockerfile, shell, toml, sql]
        additional_dependencies:
          - prettier@3.6.2
          - prettier-plugin-sh@0.18.0
          - prettier-plugin-toml@2.0.6
          - prettier-plugin-sql@0.19.2
        args: [--print-width=80, --prose-wrap=always]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
